# Generated by Django 4.2.11 on 2024-03-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
